### ISSUE TITLE
high CPU utilization with a lot of containers

### ISSUE THREAD

**Issue by bprodoehl** [pelger/docker-stats#6]
If I spin up 80 containers on a 2-core machine, the docker-stats usage example from the readme causes the Docker daemon to eat up a full core spread among two or three docker daemon processes.

It looks to me like docker-stats and docker-allcontainers are doing too many API operations when there are many containers.  I also think that for my use case, I'd be better off if it switched to non-streaming stats updates from the Docker daemon if the stats interval is longer than maybe 5 or 10 seconds.

I'm going to see what I can do to to make this library cope with lots of containers, and hopefully a PR would be welcome.

**Comment by mcollina** [comment]
Yes, a PR will be welcomed. We never tested this library with an high
amount of containers, and it is probably expected to behave this way.
Il giorno gio 7 apr 2016 alle 02:58 Brian Prodoehl notifications@github.com
ha scritto:

**Comment by bprodoehl** [comment]
This is addressed in pull request #7.
