### ISSUE TITLE
Docker stats excludes the current container

### ISSUE THREAD

**Issue by megastef** [pelger/docker-stats#9]
Recently we discovered that our monitoring container did not monitor itself. Why? Look at this:
https://github.com/pelger/docker-stats/blob/master/stats.js#L46

1) docker-stats should provide all stats including the current container. It takes resources like each other container and excluding it would lead to wrong metrics e.g. total CPU of all running containers or total memory used by all containers ...
2) I don't see how it can produce an endless loop in context of docker-stats interface (only true for Docker logs ... https://github.com/mcollina/docker-loghose/blob/cb576fb345772cf98bf56beb6906e821ed8c4500/lib/loghose.js#L39 but even there the API user could filter it out ... as we did for our debugging mode, which dumps each log). 
3) I had to do a workaround  to fix this quickly: My start script sets a different HOSTNAME env var before starting the Node.js monitoring

**Comment by mcollina** [comment]
Can you please send a PR for this as well?

**Comment by mcollina** [comment]
Fixed in 10.
